/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClickerControl: typeof import('./src/components/ClickerControl.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInputNumber: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    URadioGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.4_@tiptap+core@3.22.4_@tiptap+pm@3.22.4__@tiptap+pm@3._oxak6uugobnudbuh3qvcsk5kgi/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
